"""
Shared utilities for CareBuddy orchestrator.
Handles device selection, pipeline initialization, and logging.
"""

import logging
import torch
import shutil
from datetime import datetime
from pathlib import Path
from transformers import pipeline

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
log = logging.getLogger(__name__)

INPUT_DIR = Path("./results/input")
OUTPUT_DIR = Path("./results/output")

# Auto-select device
if torch.cuda.is_available():
    DEVICE = "cuda"
elif getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
    DEVICE = "mps"
else:
    DEVICE = "cpu"

# Choose safe dtype
if hasattr(torch, "bfloat16") and (DEVICE != "cpu"):
    DTYPE = torch.bfloat16
else:
    DTYPE = torch.float32

log.info(f"Using device={DEVICE}, dtype={DTYPE}")

# Initialize shared model pipeline
PIPE = pipeline(
    "image-text-to-text",
    model="google/medgemma-1.5-4b-it",
    torch_dtype=DTYPE,
    device=DEVICE,
)


def get_pipeline():
    """Get the shared pipeline instance."""
    return PIPE


def get_device():
    """Get the selected device."""
    return DEVICE


def get_dtype():
    """Get the selected dtype."""
    return DTYPE


def get_logger(name: str):
    """Get a logger instance for a module."""
    return logging.getLogger(name)


def archive_results(total_files: int, processed_files: int, description: str = "Comprehensive analysis report for processed medical files. It includes key insights, patterns, and observations derived from the analysis of the dataset.") -> Path:
    """
    Archive results to timestamped subfolder and create SKILL.md.
    
    Args:
        total_files: Total number of files processed
        processed_files: Number of successfully processed files
    
    Returns:
        Path to the archive folder
    """
    # Create timestamped folder name (format: YYYY-MM-DD_HH-MM-SS)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    archive_folder = OUTPUT_DIR / timestamp
    archive_folder.mkdir(parents=True, exist_ok=True)
    
    # Copy results.json
    results_file = OUTPUT_DIR / "results.json"
    if results_file.exists():
        shutil.copy(results_file, archive_folder / "results.json")
        log.info(f"Copied results.json to {archive_folder}")
    
    # Copy analysis_report.txt
    report_file = OUTPUT_DIR / "analysis_report.txt"
    if report_file.exists():
        shutil.copy(report_file, archive_folder / "analysis_report.txt")
        log.info(f"Copied analysis_report.txt to {archive_folder}")
    
    # Create SKILL.md
    success_rate = (processed_files / max(total_files, 1)) * 100
    skill_content = f"""---
name: clinical history {timestamp}
description: {description}
---

## Processing Metadata
- **Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Archive Folder**: {timestamp}

## Processing Statistics
- **Total Files**: {total_files}
- **Successfully Processed**: {processed_files}
- **Success Rate**: {success_rate:.1f}%

## System Information
- **Device Used**: {DEVICE}
- **Data Type**: {DTYPE}
- **Model**: google/medgemma-1.5-4b-it

## Output Files
- `results.json` - Structured results data. It inclues the filename and description of the analysis result for each file.
- `analysis_report.txt` - Comprehensive analysis report. It includes the summary of results and detailed insights generated by the medical model.

---
*Generated by CareBuddy Medical Analysis System*
"""
    
    skill_file = archive_folder / "SKILL.md"
    skill_file.write_text(skill_content)
    log.info(f"Created SKILL.md at {skill_file}")
    
    return archive_folder

